### ISSUE TITLE
Crash when using High Resolution resourcepacks containing 3D models

### ISSUE THREAD

**Issue by gabor6505** [amadornes/SCM-Localization-Issues#103]
## Description
When I load in to Minecraft a Resourcepack with 3D models in them (for the redstone torch and lever), if I take a redstone torch or lever in my hand and look at a circuit ready to place it, it instantly crashes with a "tesselating block model" error.

**Sorry if this is an intended feature or an already known issue.**

### [Crash-report](https://gist.github.com/gabor6505/472f3a70c6de9b7563b57ddaa1221721)
*The first crash report is when I'm holding a lever in my hand and the second is when I'm holding a redstone torch in my hand (they seem almost the same for me):*
Note: The crash-reports include OptiFine, I tested it and it does not happen without it, I only reported this bug here because it involves SCM, but if you want to, I can report it to Optifine as well. In the future it would be nice though if the mod would support 3D models imported from the Vanilla base pack.

### Versions:
**Super Circuit Maker**: 1.0.1
**OptiFine**: HD_U_D2

**If you need forge logs, mod list, or anything like that, tell me.**
**Thanks for the help!**

**Comment by amadornes** [comment]
Looks like an Optifine bug to me, yes.

Here's how my component rendering system works:
When the game loads, I create a BlockStateContainer (an object that contains a block and a set of properties) for each of my components with stone as the block the state pertains to (to avoid registering a new block for every single component), and with all the properties of that component (for example, in the case of a lever, the on/off state and the rotation).
I register this state to the game under the name of the component so Minecraft knows what models to load and where from, and whenever I need one of those models, I just do a lookup on that component's state inside Minecraft's state->model table and render it.

Apparently Optifine is getting in the way when I try to render the models for my components because it detects the block is stone, but it fails to find the property of stone that defines its variant (regular stone, andesite, diorite, etc).

I may be able to fix it on my end by changing that stone block to something like MCMultiPart's block, which hopefully shouldn't have a custom handler inside Optifine. If it doesn't work after the next update, then yes, it's an issue with Optifine I can't get around.

**Comment by amadornes** [comment]
Let me know if 1.0.2 fixed it :)

**Comment by gabor6505** [comment]
It works now, thanks for the help!

**Comment by amadornes** [comment]
\o/
