### ISSUE TITLE
Request: Repeaters on Circuits

### ISSUE THREAD

**Issue by eslachance** [amadornes/SCM-Localization-Issues#262]
Would love to have the ability to place a repeater on a circuit to get that exact same behaviour I'm expecting from repeaters.

**Comment by gDKdev** [comment]
I don't know, it has it reasons that you can't place any vanilla component on the circuit except the torch). But instead I would like a signal extender, to easily extend a pulse to a specific length, because the footprint of something like that is too big. Alternatively he could add on and off time to the ender pulsar, so you could get a longer signal.

**Comment by convict999** [comment]
Use the quarts resonator to extend signal, output from the pulsar to a resonator with 2 tick, add a bypass from resonator input and output with diode! = pulsar pulse(3 i think)+2 = 5 ticks , to extend a 1 tick pulse you will need to add 1 resonator with 1 tick for every increment of delay

**Comment by gDKdev** [comment]
@convict999 this is why i said it has a big footprint

**Comment by convict999** [comment]
they do stack :)

![2016-11-26_14 19 35](https://cloud.githubusercontent.com/assets/16072925/20640885/80e2e848-b3e3-11e6-9b47-5013d5ea96cb.png)

**Comment by gDKdev** [comment]
I will post a smaller and better design later on reddit. This place here is for bugs, issues and enhancements not for a blueprint exchange
