### ISSUE TITLE
Colour palette

### ISSUE THREAD

**Issue by convict999** [amadornes/SCM-Localization-Issues#32]
Bug. palette and brush in Lh, screwdriver in Rh, RC'ing to adjust wire connections change wire colour simultaneously.

Related. Probably a personal preference but if palette and brush in Lh, RC should only change colour if Rh empty, holding tool (not screwdriver) or wire, not when holding items that can be placed on wire. 
Especially as can often be in hitbox of multipart using chiseled me, little easy to colour by mistake.

Q. Defo a personal preference! a couple of times the standard wire being one of the 16 colours not bare redwire? has been a... distraction but not a problem.

Q. Will different colour wires automatically connect as now? 
I think its good different colour wires can connect without joiner (eg' AE fluix ducts), it would be useful if they only connect automatically if matching, but still possible.

**Comment by amadornes** [comment]
I know interaction order is broken, I'm still working on it and it's one of the features I've said multiple times I have to finish :P

How is making default wires grey a problem? I guess they can be a bit distracting? But in most cases you either need to color most of your wires, or not color any, so it's not that big of a deal :P
Also, wires automatically connecting... They'll probably stay as they are right now because if you have GGRG (G = grey, R = red) and paint the second grey one blue, how do you expect them to change their connections? You want the grey-blue and red-grey connection to stay there, but the blue-red to disappear or...? The fact that wires are colored by default makes disconnecting them automatically in a way that makes sense extremely hard

**Comment by convict999** [comment]
default grey was only ever a distraction, you will have obviously used many more scenarios than me. but when i place a long line (1/2 a block is a long line of redstone now AMA! haha) then colour it, place another parallel line i have to then separate and colour. 

If i made connections then change colour which then changed connections again id be unhappy yes, i should have said when placing wire.

not tried SP yet, your giving away free colour isnt that distracting enough? :p

**Comment by amadornes** [comment]
Well... You can hold ctrl while placing wire and that will prevent it from connecting to any already wires... And soon wire will be painted as you place it if you have the palette in your off hand :P

**Comment by convict999** [comment]
ctrl and placing wire confirmed to be awesome, thankyou :p 
i checked, doesnt show in guide, or alt for colour change, unless theres another page?
Auto colouring with palette sounds cool.

case closed :)

**Comment by amadornes** [comment]
The guide isn't by any means complete, so yeah... I wouldn't expect it to have too much info :P

**Comment by amadornes** [comment]
Fixed! http://ss.amadornes.com/ama-1474810530-935
