### ISSUE TITLE
No OpenGL context found in the current thread

### ISSUE THREAD

**Issue by XFactHD** [amadornes/SCM-Localization-Issues#328]
I know that this was brought up before but in that case OptiFine was used. In this case no performance increasing mods were used. I myself took a look at the SimpleModelFontrenderer @RainWarrior wrote some time ago and I know from that other issue that you used that for SCM. Maybe he knows what's wrong.
Crash: http://pastebin.com/xuUsZhdq

**Comment by TheOldOne822** [comment]
And here it is with JUST MCMultiPart and Super Circuit Maker.
http://pastebin.com/f80h97MF


"Fixable" by changing 'alwaysSetupTerrainOffThread' to false in the Forge config at the cost of a massive FPS drop.

Steps to recreate:
1) make sure you are on forge 12.18.3.2221 or later and alwaysSetupTerrainOffThread is true
2) place a Circuit plate down
3) apply named blueprint from mod (IE RSLatch)
4) Hide Circuit.

**Comment by JulianGmp** [comment]
So I'm gonna join in on this conversation, same issue here.
https://pastebin.com/bFudHXkL
The block however is directly at a chunk border, maybe that had some effect as well.

Running FTB Direwolf20 1.10 at version 1.12.1 (no additonal mods added)

However, I wasn't able to recreate the issue like TheOldOne822 suggested

>make sure you are on forge 12.18.3.2221 or later and alwaysSetupTerrainOffThread is true
>place a Circuit plate down
>apply named blueprint from mod (IE RSLatch)
>Hide Circuit.


also "alwaysSetupTerrainOffThread" was set to false for my by default and either way it did not work (joining Multiplayer)

**Comment by dman11235** [comment]
https://pastebin.com/a90we0XX

I'm going to third this.  I specifically went around hiding circuits to increase frame rate in my test world (it seems non-hidden circuits are very framey, which is a shame because I think they look fantastic especially with glowing redstone).  I hid a bunch right away, but I had put each of the creative tab blueprints down so I could see what they were like, what they looked like and how the logic was built.  I hid the T-latch, and game crashed with the error you guys have seen.  Subsequent attempts to enter the world have crashed immediately, same error.  Switching the Forge config to what you have said fixed it.

My theory is that it has to do with the circuits being named.  The other circuits you build aren't named.  Circuits from blueprints are named.  If someone with more time/knowledge than me were to test things, this is what I would test.  I identically copied the circuit and tried, no issue.

**Comment by Bjohnson131** [comment]
The solution is to update your graphics driver.

**Comment by TheOldOne822** [comment]
I don't have $1200 for a new GPU but I do have 6 to test on (9 if you count igpus) mixed between nvidia and AMD including vega (plus intel) and all have same issue **# on every driver tested**.
Edit if you have a magic driver that fixes it I would love to see it

**Comment by Bjohnson131** [comment]
I said driver, not card. Update the driver.

**Comment by TheOldOne822** [comment]
You didn't actually read my comment did you. I added Bold for you and the Edit about magic driver was before you replayed.

**Comment by Bjohnson131** [comment]
If you were testing updated drivers, this would not happen. Maybe in 2017, when you posted the original comment, maybe. Today's Drivers are different.Here are the settings that work on my bench:
https://prnt.sc/j5rzuj

They are the *NIGHTLY* build, make sure you choose that one.

**Comment by TheOldOne822** [comment]
AMD settings copy all, still crashing

Radeon Settings Version - 2018.0322.1825.31335
Driver Packaging Version - 17.50.33.05-180322a-326037E-RadeonSoftwareAdrenalin
Provider - Advanced Micro Devices, Inc.
2D Driver Version - 8.1.1.1634
Direct3D® Version - 9.14.10.01316
OpenGL® Version - 6.14.10.13507
OpenCL™ Version - 23.20.15033.5003
AMD Mantle Version - 9.1.10.0237
AMD Mantle API Version - 102400
AMD Audio Driver Version - 10.0.1.6
Vulkan™ Driver Version - 2.0.18
Vulkan™ API Version - 1.1.70

Edit: and screenshot
https://s26.postimg.cc/5lummhcl5/Viddriver.png
