### ISSUE TITLE
SadCircuitException

### ISSUE THREAD

**Issue by marcin212** [amadornes/SCM-Localization-Issues#38]
Just right click on circuit. It was random.
server-console-log: http://hastebin.com/necokevimo.vbs
screen: https://img.bymarcin.com/screenshot-2016-10-27_22-06-34.png

**Comment by Matrix89** [comment]
It should be SadCircuitException.

**Comment by amadornes** [comment]
RC4 will have a better error handler that can take care of any issues, and optionally revert to the previous state. It will also automatically gist the crashlog + blueprint prior to crash + blueprint post crash so you can send me the link and I can analyze it :)
Also, I assume the issue will be fixed in RC4 because I'm rewriting wires from the ground up to make a lot more sense :P

**Comment by Matrix89** [comment]
Ok, we are waiting for a new build.

**Comment by amadornes** [comment]
Okay, I think I've fixed it. I think it was due to the vertical wire issues, even though it was crashing the input panel.
